### ISSUE TITLE
Split initial, systemC, toolchain clone/build stages

### ISSUE THREAD

**Issue by ghost** [mperov/docker-ubuntu16.04_builder_ergochip-toolchain#3]
Can we make separate, non-repeating 'stages' for:

* initial ubuntu image configuration
* SystemC installation
* getting toolchain sources
* building the toolchain
* installer building

The thing is - every attempt to create a container (e.g. after fixing any errors during previous attempt) leads to downloading, installing etc. full package tree of ubuntu, systemc, toolchain and so on, which takes a long time, traffic and increasing amount of failed containers:

<img width="701" alt="Снимок экрана 2020-12-21 в 14 23 48" src="https://user-images.githubusercontent.com/3541487/102772214-2c2a6d00-4398-11eb-9abb-e18c56dcf0c7.png">

If there is 'a way it should go' - how to shorten these actions to save initial config time?

**Comment by mperov** [comment]
It' a pity, initialising of docker image is whole process. And we can't divide it on stages. There is way how to decrease image, but sources should be added to image, but this sources are commercial secret.

**Comment by mperov** [comment]
And why? We don't often build installer;)

**Comment by ghost** [comment]
> It' a pity, initialising of docker image is whole process. And we can't divide it on stages. There is way how to decrease image, but sources should be added to image, but this sources are commercial secret.

Okay, I get that full stack of git repos work could be replaced only by using locally cloned copy, which can be deployed by using `COPY`, no problem with that.

Can at least ubuntu image with all of the required packages installed be processed once and them re-deployed on a currently building container?

**Comment by ghost** [comment]
> And why? We don't often build installer;)

We do not, but as project updates it would be great to simply run `make` and then build final installer instead of re-cloning and re-building full repository.

**Comment by mperov** [comment]
> > It' a pity, initialising of docker image is whole process. And we can't divide it on stages. There is way how to decrease image, but sources should be added to image, but this sources are commercial secret.
> 
> Okay, I get that full stack of git repos work could be replaced only by using locally cloned copy, which can be deployed by using `COPY`, no problem with that.
> 
> Can at least ubuntu image with all of the required packages installed be processed once and them re-deployed on a currently building container?

COPY requires git repo in host machine. It isn't flexible :( Docker allows to run container on remote server, your solution makes it impossible.

Yes, we can, but this project for other task. :)

**Comment by mperov** [comment]
> > And why? We don't often build installer;)
> 
> We do not, but as project updates it would be great to simply run `make` and then build final installer instead of re-cloning and re-building full repository.

The re-cloning and re-building full repository are good testing all project ;) And why should we build the installer on each commit?
